; Generated by Coffee-AHK/0.0.89
class Ｔest {
  __New(name) {
    this.name := name
    (Func("test_2").Bind(λ)).Call(this)
  }
  greet := Func("test_1").Bind({}, this)
}
test_1(λ, ℓthis) {
  this := ℓthis
  return console.log.Call("Hello, " . (this.name) . "!")
}
test_2(λ, ℓthis) {
  this := ℓthis
  return this.name
}