global ℓarray := [1, 2]
global a := ℓarray[1]
global b := ℓarray[2]
ℓarray := arr
global x := ℓarray[1]
global y := ℓarray[2]
global z := ℓarray[3]
global ℓobject := person
global name := ℓobject["name"]
global age := ℓobject["age"]
ℓobject := obj
global foo := ℓobject["foo"]
global bar := ℓobject["bar"]