; generated by coffee-ahk/0.0.1


#KeyHistory 0
#MaxThreads 20
#NoEnv
#Persistent
#SingleInstance Force
#UseHook

CoordMode Mouse, Client
CoordMode Pixel, Client
CoordMode ToolTip, Client
SendMode Event
SetBatchLines 100ms
SetKeyDelay 0, 50
SetMouseDelay 0, 50

global $ := {}
$.alert(message := "") {
  MsgBox % message
  return message
}
$.beep() {
  SoundBeep
}
$.exit() {
  ExitApp
}
$.click(input) {
  if (!input) {
    Click
    return
  }
  Click % StrReplace input, ':', ' '
}
$.abs(n) { ; math
  return Abs(n)
}
$.ceil(n) {
  return Ceil(n)
}
$.floor(n) {
  return Floor(n)
}
$.round(n) {
  return Round(n)
}
$.move(x := 0, y := 0, speed := 0) {
  MouseMove x, y, speed
  return [x, y, speed]
}
$.now() {
  return A_TickCount
}
$.reload() {
  Reload
}
$.sleep(time := 0) {
  Sleep % time
}
$.trim(input) { ; trim
  return Trim input
}
$.trimStart(input) {
  return LTrim input
}
$.trimEnd(input) {
  return RTrim input
}
$.alert($.trim("timestamp is " . ($.now()) . ""))
