global a := "string"
a := "" . (a) . ""
a := "" . (1 - 1) . " === " . (1 - 1) . "?"
a := "line 1 line 2 line 3"
a := "line " . (1) . " line " . (2) . " line " . (3) . ""
a := "<strong>cup of coffee-ahk</strong>"
a := "<strong>cup of " . (name) . "</strong>"
a := "call(""http" . ("s") . """)"