; Generated by Coffee-AHK/0.0.100
global ℓci_0c7bugpf3jp := Func("salt_1").Bind({})
salt_1(λ, ℓarr, ℓidx) {
  if ℓidx is Number
  {
    if (ℓidx < 0) {
      return ℓarr.Length() + ℓidx + 1
    }
    return ℓidx + 1
  }
  return ℓidx
}
class ＫeyＢindingＳhell {
  __New() {
    this.mapBound := {}
    this.mapCallback := {}
    this.mapPrevented := {}
  }
  prepare := Func("0c7bugpf3jp_3").Bind({}, this)
  fire := Func("0c7bugpf3jp_1").Bind({}, this)
}
0c7bugpf3jp_1(λ, ℓthis, key) {
  this := ℓthis
  λ.key := key
  return λ.console.log.Call("Firing: ".key)
}
0c7bugpf3jp_2(λ, ℓthis) {
  this := ℓthis
  return this.fire.Call(λ.key)
}
0c7bugpf3jp_3(λ, ℓthis, key) {
  this := ℓthis
  λ.key := key
  if (this.mapCallback[ℓci_0c7bugpf3jp.Call(.mapCallback, λ.key)]) {
    return
  }
  this.mapBound[ℓci_0c7bugpf3jp.Call(.mapBound, λ.key)] := Func("0c7bugpf3jp_2").Bind(λ, this)
  this.mapCallback[ℓci_0c7bugpf3jp.Call(.mapCallback, λ.key)] := []
  this.mapPrevented[ℓci_0c7bugpf3jp.Call(.mapPrevented, λ.key)] := false
  return
}