; Generated by Coffee-AHK/0.0.39
; Generated by Coffee-AHK/0.0.26
global fn1 := Func("ahk_2")
global fn2 := Func("ahk_1")
return {fn1, fn2}
ahk_1() {
  return 2
}
ahk_2() {
  return 1
}

global coffee := (Func("ahk_3")).Call()
global js := ""
js =
(
alert('hello')
alert('world')
)
global yaml := {a: 1, b: "text", c: [1, 2, 3], d: {a: 1, b: 2}}
ahk_1() {
  return 2
}
ahk_2() {
  return 1
}
ahk_3() {
  module := {}
  module.fn1 := Func("ahk_2")
  module.fn2 := Func("ahk_1")
  return module
}
