; Generated by Coffee-AHK/0.0.46

a := 1
b := a + 1
MsgBox, % b

global __ahk_module_1__ := {a: 1, b: 2}
global __ahk_module_2__ := (Func("ahk_3")).Call()
global __ahk_module_3__ := (Func("ahk_1")).Call()
global b := __ahk_module_1__
global alert := __ahk_module_2__
alert.Call(b.a)
global m := __ahk_module_3__
m.alert.Call(m.data.b)
ahk_1() {
  alert := __ahk_module_2__
  b := __ahk_module_1__
  return {alert: alert, data: b}
}
ahk_2(msg) {
  MsgBox, % msg
}
ahk_3() {
  return Func("ahk_2")
}
