import { getName, read, write } from 'fire-keeper'
import iconv from 'iconv-lite'

import type { PartialOptions } from '..'
import type Item from '../models/Item'

const getVersion = async () => {
  const { version } = (await read<{
    version: string
  }>('./package.json')) ?? {
    version: 'unknown',
  }
  return version
}

const main = async (
  source: string,
  data: {
    ast: Item[]
    content: string
  },
  options: PartialOptions,
): Promise<void> => {
  const { basename, dirname } = getName(source)

  await write(
    `${dirname}/${basename}.ahk`,
    iconv
      .encode(
        options.metadata
          ? [
              `; Generated by Coffee-AHK/${await getVersion()}`,
              data.content,
            ].join('\n')
          : data.content,
        'utf8',
        {
          addBOM: true,
        },
      )
      .toString(),
  )

  if (options.ast) await write(`${dirname}/${basename}.ast.json`, data.ast)
}

export default main
