// function

function main(
  listMode: string[]
): string[] {

  let listResult = [
    '; generated by coffee-basic/0.0.3'
  ]

  // mode admin
  if (listMode.includes('admin'))
    listResult = [
      ...listResult,
      '',
      'if (A_IsAdmin != true) {',
      '  Run *RunAs "%A_ScriptFullPath%"',
      '  ExitApp',
      '}'
    ]

  listResult = [
    ...listResult,
    '',
    '#KeyHistory 0',
    '#MaxThreads 20',
    '#NoEnv',
    '#Persistent',
    '#SingleInstance Force',
    '#UseHook',
    '',
    'CoordMode Mouse, Client',
    'CoordMode Pixel, Client',
    'CoordMode ToolTip, Client',
    'SendMode Event',
    'SetBatchLines 100ms',
    'SetKeyDelay 0, 50',
    'SetMouseDelay 0, 50'
  ]

  return listResult
}

// export
export default main